spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
  jpa:
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret: ba570e06-8b32-46aa-a1ad-4ae069d7b4c7